// {
//   First_Name: "First_Name",
//   Last_Name: "Last_Name",
//   contact: "Phone_Number",
//   city: "City",
//   state: "State",
//   language: "Language",
//   email: "Email_Address",
//   password: "Password",
//   rate: "Price",
//   id: "National ID",
//   barID: "BAR ID ",
//   barYear: "Enrollment_Date",
//   specialties: "Speciality",
//   summary: "Professional Summary",
// },

const users = [
  {
    First_Name: "Lawyer1",
    Last_Name: "Llast1",
    contact: "2200220001",
    city: "Bishnupur",
    state: "Manipur",
    language: "Hindi, English",
    email: "lawyer1@aa.com",
    password: "123456",
    rate: "45",
    id: "NATIONAL_ID_1",
    barID: "BAR_ID_1",
    barYear: "38712",
    specialties: "Divorce & Child Custody, Property & Real Estate",
    summary: "Summary written by Lawyer",
  },
  {
    First_Name: "Lawyer2",
    Last_Name: "Llast2",
    contact: "2200220002",
    city: "Churachandpur",
    state: "Manipur",
    language: "Hindi, English",
    email: "lawyer2@aa.com",
    password: "123456",
    rate: "45",
    id: "NATIONAL_ID_2",
    barID: "BAR_ID_2",
    barYear: "40296",
    specialties: "Property & Real Estate, Cheque Bounce & Money Recovery",
    summary:
      "I have been practicing from last 5 years before the Hon'ble Rajasthan HC, District Courts, Tribunals amd other forums. I'm a third generation lawyer having 40 plus years of goodwill and standing in the legal industry.",
  },
  {
    First_Name: "Lawyer3",
    Last_Name: "Llast3",
    contact: "2200220003",
    city: "Imphal",
    state: "Manipur",
    language: "Hindi, English",
    email: "lawyer3@aa.com",
    password: "123456",
    rate: "38",
    id: "NATIONAL_ID_3",
    barID: "BAR_ID_3",
    barYear: "38104",
    specialties: " Cheque Bounce & Money Recovery, Employment Issues",
    summary:
      "With 30 years of professional lineage as a second-generation lawyer in the Delhi High Court, Bombay High Court Karnataka High Court, Telangana High Court, District Courts across India and Supreme Court Of India. I am a seasoned legal expert with a wealth of experience in a wide range of legal matters. As a representative of the Delhi Police, I am well-versed in providing legal advisory, drafting, and representing services across various courts in India. I have specialized expertise in civil, criminal, and corporate laws, with particular proficiency in drafting suits, writs, petitions, appeals, revisions, and complaints related to debt recovery, cheque bounce matters, rent control act, property disputes, and matrimonial disputes. Additionally, I have extensive experience in handling consumer complaints, FSSAI-related matters, and service matters. My expertise in drafting quality legal documents and agreements is unparalleled. I have experience drafting and professionally vetting a range of legal documents and agreements, including Master Service Agreements, Commercial Leases, Consortium Agreements, Tripartite Agreements, RFQs, Letters of Intent, MOUs, Celebrity Agreements, Endorsement Agreements, License Agreements, Sub-Licensing Agreements, Sub-Contracting, Third-Party Agreements, Sale Deeds, Corporate Lease Agreements, and Development Agreements in the real estate sector. With my extensive knowledge and experience in the legal industry, I am confident in my ability to provide expert legal advice and support to clients across a range of industries and sectors.",
  },
  {
    First_Name: "Lawyer4",
    Last_Name: "Llast4",
    contact: "2200220004",
    city: "Jammu",
    state: "Jammu and Kashmir",
    language: "Hindi, English",
    email: "lawyer4@aa.com",
    password: "123456",
    rate: "22",
    id: "NATIONAL_ID_4",
    barID: "BAR_ID_4",
    barYear: "43751",
    specialties: "Employment Issues, Consumer Protection, Civil Matter",
    summary: "Lawyer Supreme court of India",
  },
  {
    First_Name: "Lawyer5",
    Last_Name: "Llast5",
    contact: "2200220005",
    city: "Katra",
    state: "Jammu and Kashmir",
    language: "Hindi, English",
    email: "lawyer5@aa.com",
    password: "123456",
    rate: "40",
    id: "NATIONAL_ID_5",
    barID: "BAR_ID_5",
    barYear: "44228",
    specialties: "Consumer Protection, Civil Matters, Cyber Crime",
    summary: "dealing with civil, criminal, Dop, Place, mvop ect cases. ",
  },
  {
    First_Name: "Lawyer6",
    Last_Name: "Llast6",
    contact: "2200220006",
    city: "Pulwama",
    state: "Jammu and Kashmir",
    language: "Hindi, English",
    email: "lawyer6@aa.com",
    password: "123456",
    rate: "35",
    id: "NATIONAL_ID_6",
    barID: "BAR_ID_6",
    barYear: "34401",
    specialties:
      "Divorce & Child Custody, Property & Real Estate, Civil Matters, Cyber Crime, ",
    summary: "Fifteen years experience lawyer.",
  },
  {
    First_Name: "Lawyer7",
    Last_Name: "Llast7",
    contact: "2200220007",
    city: "Srinagar",
    state: "Jammu and Kashmir",
    language: "Hindi, English",
    email: "lawyer7@aa.com",
    password: "123456",
    rate: "50",
    id: "NATIONAL_ID_7",
    barID: "BAR_ID_7",
    barYear: "42577",
    specialties: "Civil Matters, Cyber Crime, Other Legal Problem",
    summary:
      "Advocate A. Ashok Kumar has been practising for 9 years in Civil, Criminal & Family matters cases and handling the matters ethically and professionally. He also handles the NI Act, Recovery, Medical N",
  },
  {
    First_Name: "Lawyer8",
    Last_Name: "Llast8",
    contact: "2200220008",
    city: "Ambala",
    state: "Haryana",
    language: "Hindi, English",
    email: "lawyer8@aa.com",
    password: "123456",
    rate: "38",
    id: "NATIONAL_ID_8",
    barID: "BAR_ID_8",
    barYear: "41641",
    specialties:
      "Property & Real Estate, Consumer Protection, Civil Matters, Cyber Crime, Criminal Matter",
    summary: "Summary written by Lawyer",
  },
  {
    First_Name: "Lawyer9",
    Last_Name: "Llast9",
    contact: "2200220009",
    city: "Faridabad",
    state: "Haryana",
    language: "Hindi, English",
    email: "lawyer9@aa.com",
    password: "123456",
    rate: "40",
    id: "NATIONAL_ID_9",
    barID: "BAR_ID_9",
    barYear: "38542",
    specialties: "Divorce & Child Custody, Property & Real Estate, Cyber Crime",
    summary:
      "I have been practicing from last 5 years before the Hon'ble Rajasthan HC, District Courts, Tribunals amd other forums. I'm a third generation lawyer having 40 plus years of goodwill and standing in the legal industry.",
  },
  {
    First_Name: "Lawyer10",
    Last_Name: "Llast10",
    contact: "2200220010",
    city: "Gurgaon",
    state: "Haryana",
    language: "Hindi, English",
    email: "lawyer10@aa.com",
    password: "123456",
    rate: "43",
    id: "NATIONAL_ID_10",
    barID: "BAR_ID_10",
    barYear: "42654",
    specialties: "Divorce & Child Custody, Property & Real Estate",
    summary:
      "With 30 years of professional lineage as a second-generation lawyer in the Delhi High Court, Bombay High Court Karnataka High Court, Telangana High Court, District Courts across India and Supreme Court Of India. I am a seasoned legal expert with a wealth of experience in a wide range of legal matters. As a representative of the Delhi Police, I am well-versed in providing legal advisory, drafting, and representing services across various courts in India. I have specialized expertise in civil, criminal, and corporate laws, with particular proficiency in drafting suits, writs, petitions, appeals, revisions, and complaints related to debt recovery, cheque bounce matters, rent control act, property disputes, and matrimonial disputes. Additionally, I have extensive experience in handling consumer complaints, FSSAI-related matters, and service matters. My expertise in drafting quality legal documents and agreements is unparalleled. I have experience drafting and professionally vetting a range of legal documents and agreements, including Master Service Agreements, Commercial Leases, Consortium Agreements, Tripartite Agreements, RFQs, Letters of Intent, MOUs, Celebrity Agreements, Endorsement Agreements, License Agreements, Sub-Licensing Agreements, Sub-Contracting, Third-Party Agreements, Sale Deeds, Corporate Lease Agreements, and Development Agreements in the real estate sector. With my extensive knowledge and experience in the legal industry, I am confident in my ability to provide expert legal advice and support to clients across a range of industries and sectors.",
  },
  {
    First_Name: "Lawyer11",
    Last_Name: "Llast11",
    contact: "2200220011",
    city: "Panipat",
    state: "Haryana",
    language: "Hindi, English",
    email: "lawyer11@aa.com",
    password: "123456",
    rate: "47",
    id: "NATIONAL_ID_11",
    barID: "BAR_ID_11",
    barYear: "37004",
    specialties: "Property & Real Estate, Cheque Bounce & Money Recovery",
    summary: "Lawyer Supreme court of India",
  },
  {
    First_Name: "Lawyer12",
    Last_Name: "Llast12",
    contact: "2200220012",
    city: "Mumbai",
    state: "Maharashtra",
    language: "Hindi, English, Marathi",
    email: "lawyer12@aa.com",
    password: "123456",
    rate: "37",
    id: "NATIONAL_ID_12",
    barID: "BAR_ID_12",
    barYear: "39055",
    specialties: " Cheque Bounce & Money Recovery, Employment Issues",
    summary: "dealing with civil, criminal, Dop, Place, mvop ect cases. ",
  },
  {
    First_Name: "Lawyer13",
    Last_Name: "Llast13",
    contact: "2200220013",
    city: "Mumbai Suburban",
    state: "Maharashtra",
    language: "Hindi, English, Marathi",
    email: "lawyer13@aa.com",
    password: "123456",
    rate: "47",
    id: "NATIONAL_ID_13",
    barID: "BAR_ID_13",
    barYear: "32746",
    specialties: "Employment Issues, Consumer Protection, Civil Matter",
    summary: "Fifteen years experience lawyer.",
  },
  {
    First_Name: "Lawyer14",
    Last_Name: "Llast14",
    contact: "2200220014",
    city: "Nagpur",
    state: "Maharashtra",
    language: "Hindi, English, Marathi",
    email: "lawyer14@aa.com",
    password: "123456",
    rate: "35",
    id: "NATIONAL_ID_14",
    barID: "BAR_ID_14",
    barYear: "33479",
    specialties: "Consumer Protection, Civil Matters, Cyber Crime",
    summary:
      "Advocate A. Ashok Kumar has been practising for 9 years in Civil, Criminal & Family matters cases and handling the matters ethically and professionally. He also handles the NI Act, Recovery, Medical N",
  },
  {
    First_Name: "Lawyer15",
    Last_Name: "Llast15",
    contact: "2200220015",
    city: "Nashik",
    state: "Maharashtra",
    language: "Hindi, English, Marathi",
    email: "lawyer15@aa.com",
    password: "123456",
    rate: "41",
    id: "NATIONAL_ID_15",
    barID: "BAR_ID_15",
    barYear: "32622",
    specialties:
      "Divorce & Child Custody, Property & Real Estate, Civil Matters, Cyber Crime, ",
    summary: "Summary written by Lawyer",
  },
  {
    First_Name: "Lawyer16",
    Last_Name: "Llast16",
    contact: "2200220016",
    city: "Navi Mumbai",
    state: "Maharashtra",
    language: "Hindi, English, Marathi",
    email: "lawyer16@aa.com",
    password: "123456",
    rate: "42",
    id: "NATIONAL_ID_16",
    barID: "BAR_ID_16",
    barYear: "41759",
    specialties: "Civil Matters, Cyber Crime, Other Legal Problem",
    summary:
      "I have been practicing from last 5 years before the Hon'ble Rajasthan HC, District Courts, Tribunals amd other forums. I'm a third generation lawyer having 40 plus years of goodwill and standing in the legal industry.",
  },
  {
    First_Name: "Lawyer17",
    Last_Name: "Llast17",
    contact: "2200220017",
    city: "Pune",
    state: "Maharashtra",
    language: "Hindi, English, Marathi",
    email: "lawyer17@aa.com",
    password: "123456",
    rate: "44",
    id: "NATIONAL_ID_17",
    barID: "BAR_ID_17",
    barYear: "39815",
    specialties:
      "Property & Real Estate, Consumer Protection, Civil Matters, Cyber Crime, Criminal Matter",
    summary:
      "With 30 years of professional lineage as a second-generation lawyer in the Delhi High Court, Bombay High Court Karnataka High Court, Telangana High Court, District Courts across India and Supreme Court Of India. I am a seasoned legal expert with a wealth of experience in a wide range of legal matters. As a representative of the Delhi Police, I am well-versed in providing legal advisory, drafting, and representing services across various courts in India. I have specialized expertise in civil, criminal, and corporate laws, with particular proficiency in drafting suits, writs, petitions, appeals, revisions, and complaints related to debt recovery, cheque bounce matters, rent control act, property disputes, and matrimonial disputes. Additionally, I have extensive experience in handling consumer complaints, FSSAI-related matters, and service matters. My expertise in drafting quality legal documents and agreements is unparalleled. I have experience drafting and professionally vetting a range of legal documents and agreements, including Master Service Agreements, Commercial Leases, Consortium Agreements, Tripartite Agreements, RFQs, Letters of Intent, MOUs, Celebrity Agreements, Endorsement Agreements, License Agreements, Sub-Licensing Agreements, Sub-Contracting, Third-Party Agreements, Sale Deeds, Corporate Lease Agreements, and Development Agreements in the real estate sector. With my extensive knowledge and experience in the legal industry, I am confident in my ability to provide expert legal advice and support to clients across a range of industries and sectors.",
  },
  {
    First_Name: "Lawyer18",
    Last_Name: "Llast18",
    contact: "2200220018",
    city: "Yarada",
    state: "Andhra Pradesh",
    language: "Hindi, English",
    email: "lawyer18@aa.com",
    password: "123456",
    rate: "22",
    id: "NATIONAL_ID_18",
    barID: "BAR_ID_18",
    barYear: "34615",
    specialties: "Divorce & Child Custody, Property & Real Estate, Cyber Crime",
    summary: "Lawyer Supreme court of India",
  },
  {
    First_Name: "Lawyer19",
    Last_Name: "Llast19",
    contact: "2200220019",
    city: "pedda nakkalapalem",
    state: "Andhra Pradesh",
    language: "Hindi, English",
    email: "lawyer19@aa.com",
    password: "123456",
    rate: "42",
    id: "NATIONAL_ID_19",
    barID: "BAR_ID_19",
    barYear: "42930",
    specialties: "Divorce & Child Custody, Property & Real Estate",
    summary: "dealing with civil, criminal, Dop, Place, mvop ect cases. ",
  },
  {
    First_Name: "Lawyer20",
    Last_Name: "Llast20",
    contact: "2200220020",
    city: "vadlamuru",
    state: "Andhra Pradesh",
    language: "Hindi, English",
    email: "lawyer20@aa.com",
    password: "123456",
    rate: "40",
    id: "NATIONAL_ID_20",
    barID: "BAR_ID_20",
    barYear: "34484",
    specialties: "Property & Real Estate, Cheque Bounce & Money Recovery",
    summary: "Fifteen years experience lawyer.",
  },
  {
    First_Name: "Lawyer21",
    Last_Name: "Llast21",
    contact: "2200220021",
    city: "Ajmer",
    state: "Rajasthan",
    language: "Hindi, English",
    email: "lawyer21@aa.com",
    password: "123456",
    rate: "50",
    id: "NATIONAL_ID_21",
    barID: "BAR_ID_21",
    barYear: "35191",
    specialties: " Cheque Bounce & Money Recovery, Employment Issues",
    summary:
      "Advocate A. Ashok Kumar has been practising for 9 years in Civil, Criminal & Family matters cases and handling the matters ethically and professionally. He also handles the NI Act, Recovery, Medical N",
  },
  {
    First_Name: "Lawyer22",
    Last_Name: "Llast22",
    contact: "2200220022",
    city: "Jaipur",
    state: "Rajasthan",
    language: "Hindi, English",
    email: "lawyer22@aa.com",
    password: "123456",
    rate: "43",
    id: "NATIONAL_ID_22",
    barID: "BAR_ID_22",
    barYear: "38682",
    specialties: "Employment Issues, Consumer Protection, Civil Matter",
    summary: "Summary written by Lawyer",
  },
  {
    First_Name: "Lawyer23",
    Last_Name: "Llast23",
    contact: "2200220023",
    city: "Kota",
    state: "Rajasthan",
    language: "Hindi, English",
    email: "lawyer23@aa.com",
    password: "123456",
    rate: "41",
    id: "NATIONAL_ID_23",
    barID: "BAR_ID_23",
    barYear: "34405",
    specialties: "Consumer Protection, Civil Matters, Cyber Crime",
    summary:
      "I have been practicing from last 5 years before the Hon'ble Rajasthan HC, District Courts, Tribunals amd other forums. I'm a third generation lawyer having 40 plus years of goodwill and standing in the legal industry.",
  },
  {
    First_Name: "Lawyer24",
    Last_Name: "Llast24",
    contact: "2200220024",
    city: "Central Delhi",
    state: "Delhi",
    language: "Hindi, English, Punjabi",
    email: "lawyer24@aa.com",
    password: "123456",
    rate: "29",
    id: "NATIONAL_ID_24",
    barID: "BAR_ID_24",
    barYear: "36200",
    specialties:
      "Divorce & Child Custody, Property & Real Estate, Civil Matters, Cyber Crime, ",
    summary:
      "With 30 years of professional lineage as a second-generation lawyer in the Delhi High Court, Bombay High Court Karnataka High Court, Telangana High Court, District Courts across India and Supreme Court Of India. I am a seasoned legal expert with a wealth of experience in a wide range of legal matters. As a representative of the Delhi Police, I am well-versed in providing legal advisory, drafting, and representing services across various courts in India. I have specialized expertise in civil, criminal, and corporate laws, with particular proficiency in drafting suits, writs, petitions, appeals, revisions, and complaints related to debt recovery, cheque bounce matters, rent control act, property disputes, and matrimonial disputes. Additionally, I have extensive experience in handling consumer complaints, FSSAI-related matters, and service matters. My expertise in drafting quality legal documents and agreements is unparalleled. I have experience drafting and professionally vetting a range of legal documents and agreements, including Master Service Agreements, Commercial Leases, Consortium Agreements, Tripartite Agreements, RFQs, Letters of Intent, MOUs, Celebrity Agreements, Endorsement Agreements, License Agreements, Sub-Licensing Agreements, Sub-Contracting, Third-Party Agreements, Sale Deeds, Corporate Lease Agreements, and Development Agreements in the real estate sector. With my extensive knowledge and experience in the legal industry, I am confident in my ability to provide expert legal advice and support to clients across a range of industries and sectors.",
  },
  {
    First_Name: "Lawyer25",
    Last_Name: "Llast25",
    contact: "2200220025",
    city: "Delhi",
    state: "Delhi",
    language: "Hindi, English, Punjabi",
    email: "lawyer25@aa.com",
    password: "123456",
    rate: "48",
    id: "NATIONAL_ID_25",
    barID: "BAR_ID_25",
    barYear: "35761",
    specialties: "Civil Matters, Cyber Crime, Other Legal Problem",
    summary: "Lawyer Supreme court of India",
  },
  {
    First_Name: "Lawyer26",
    Last_Name: "Llast26",
    contact: "2200220026",
    city: "East Delhi",
    state: "Delhi",
    language: "Hindi, English, Punjabi",
    email: "lawyer26@aa.com",
    password: "123456",
    rate: "26",
    id: "NATIONAL_ID_26",
    barID: "BAR_ID_26",
    barYear: "38490",
    specialties:
      "Property & Real Estate, Consumer Protection, Civil Matters, Cyber Crime, Criminal Matter",
    summary: "dealing with civil, criminal, Dop, Place, mvop ect cases. ",
  },
  {
    First_Name: "Lawyer27",
    Last_Name: "Llast27",
    contact: "2200220027",
    city: "New Delhi",
    state: "Delhi",
    language: "Hindi, English, Punjabi",
    email: "lawyer27@aa.com",
    password: "123456",
    rate: "21",
    id: "NATIONAL_ID_27",
    barID: "BAR_ID_27",
    barYear: "34564",
    specialties: "Divorce & Child Custody, Property & Real Estate, Cyber Crime",
    summary: "Fifteen years experience lawyer.",
  },
  {
    First_Name: "Lawyer28",
    Last_Name: "Llast28",
    contact: "2200220028",
    city: "North Delhi",
    state: "Delhi",
    language: "Hindi, English, Punjabi",
    email: "lawyer28@aa.com",
    password: "123456",
    rate: "34",
    id: "NATIONAL_ID_28",
    barID: "BAR_ID_28",
    barYear: "35667",
    specialties: "Divorce & Child Custody, Property & Real Estate",
    summary:
      "Advocate A. Ashok Kumar has been practising for 9 years in Civil, Criminal & Family matters cases and handling the matters ethically and professionally. He also handles the NI Act, Recovery, Medical N",
  },
  {
    First_Name: "Lawyer29",
    Last_Name: "Llast29",
    contact: "2200220029",
    city: "North East Delhi",
    state: "Delhi",
    language: "Hindi, English, Punjabi",
    email: "lawyer29@aa.com",
    password: "123456",
    rate: "20",
    id: "NATIONAL_ID_29",
    barID: "BAR_ID_29",
    barYear: "34843",
    specialties: "Property & Real Estate, Cheque Bounce & Money Recovery",
    summary: "Summary written by Lawyer",
  },
  {
    First_Name: "Lawyer30",
    Last_Name: "Llast30",
    contact: "2200220030",
    city: "North West Delhi",
    state: "Delhi",
    language: "Hindi, English, Punjabi",
    email: "lawyer30@aa.com",
    password: "123456",
    rate: "28",
    id: "NATIONAL_ID_30",
    barID: "BAR_ID_30",
    barYear: "43402",
    specialties: " Cheque Bounce & Money Recovery, Employment Issues",
    summary:
      "I have been practicing from last 5 years before the Hon'ble Rajasthan HC, District Courts, Tribunals amd other forums. I'm a third generation lawyer having 40 plus years of goodwill and standing in the legal industry.",
  },
  {
    First_Name: "Lawyer31",
    Last_Name: "Llast31",
    contact: "2200220031",
    city: "South Delhi",
    state: "Delhi",
    language: "Hindi, English, Punjabi",
    email: "lawyer31@aa.com",
    password: "123456",
    rate: "23",
    id: "NATIONAL_ID_31",
    barID: "BAR_ID_31",
    barYear: "43941",
    specialties: "Employment Issues, Consumer Protection, Civil Matter",
    summary:
      "With 30 years of professional lineage as a second-generation lawyer in the Delhi High Court, Bombay High Court Karnataka High Court, Telangana High Court, District Courts across India and Supreme Court Of India. I am a seasoned legal expert with a wealth of experience in a wide range of legal matters. As a representative of the Delhi Police, I am well-versed in providing legal advisory, drafting, and representing services across various courts in India. I have specialized expertise in civil, criminal, and corporate laws, with particular proficiency in drafting suits, writs, petitions, appeals, revisions, and complaints related to debt recovery, cheque bounce matters, rent control act, property disputes, and matrimonial disputes. Additionally, I have extensive experience in handling consumer complaints, FSSAI-related matters, and service matters. My expertise in drafting quality legal documents and agreements is unparalleled. I have experience drafting and professionally vetting a range of legal documents and agreements, including Master Service Agreements, Commercial Leases, Consortium Agreements, Tripartite Agreements, RFQs, Letters of Intent, MOUs, Celebrity Agreements, Endorsement Agreements, License Agreements, Sub-Licensing Agreements, Sub-Contracting, Third-Party Agreements, Sale Deeds, Corporate Lease Agreements, and Development Agreements in the real estate sector. With my extensive knowledge and experience in the legal industry, I am confident in my ability to provide expert legal advice and support to clients across a range of industries and sectors.",
  },
  {
    First_Name: "Lawyer32",
    Last_Name: "Llast32",
    contact: "2200220032",
    city: "South West Delhi",
    state: "Delhi",
    language: "Hindi, English, Punjabi",
    email: "lawyer32@aa.com",
    password: "123456",
    rate: "28",
    id: "NATIONAL_ID_32",
    barID: "BAR_ID_32",
    barYear: "44851",
    specialties: "Consumer Protection, Civil Matters, Cyber Crime",
    summary: "Lawyer Supreme court of India",
  },
  {
    First_Name: "Lawyer33",
    Last_Name: "Llast33",
    contact: "2200220033",
    city: "West Delhi",
    state: "Delhi",
    language: "Hindi, English, Punjabi",
    email: "lawyer33@aa.com",
    password: "123456",
    rate: "23",
    id: "NATIONAL_ID_33",
    barID: "BAR_ID_33",
    barYear: "36952",
    specialties:
      "Divorce & Child Custody, Property & Real Estate, Civil Matters, Cyber Crime, ",
    summary: "dealing with civil, criminal, Dop, Place, mvop ect cases. ",
  },
  {
    First_Name: "Lawyer34",
    Last_Name: "Llast34",
    contact: "2200220034",
    city: "Dehradun",
    state: "Uttarakhand",
    language: "Hindi, English",
    email: "lawyer34@aa.com",
    password: "123456",
    rate: "41",
    id: "NATIONAL_ID_34",
    barID: "BAR_ID_34",
    barYear: "44415",
    specialties: "Civil Matters, Cyber Crime, Other Legal Problem",
    summary: "Fifteen years experience lawyer.",
  },
  {
    First_Name: "Lawyer35",
    Last_Name: "Llast35",
    contact: "2200220035",
    city: "Haldwani",
    state: "Uttarakhand",
    language: "Hindi, English",
    email: "lawyer35@aa.com",
    password: "123456",
    rate: "31",
    id: "NATIONAL_ID_35",
    barID: "BAR_ID_35",
    barYear: "34253",
    specialties:
      "Property & Real Estate, Consumer Protection, Civil Matters, Cyber Crime, Criminal Matter",
    summary:
      "Advocate A. Ashok Kumar has been practising for 9 years in Civil, Criminal & Family matters cases and handling the matters ethically and professionally. He also handles the NI Act, Recovery, Medical N",
  },
  {
    First_Name: "Lawyer36",
    Last_Name: "Llast36",
    contact: "2200220036",
    city: "Haridwar",
    state: "Uttarakhand",
    language: "Hindi, English",
    email: "lawyer36@aa.com",
    password: "123456",
    rate: "35",
    id: "NATIONAL_ID_36",
    barID: "BAR_ID_36",
    barYear: "41968",
    specialties: "Divorce & Child Custody, Property & Real Estate, Cyber Crime",
    summary: "Summary written by Lawyer",
  },
  {
    First_Name: "Lawyer37",
    Last_Name: "Llast37",
    contact: "2200220037",
    city: "Roorkee",
    state: "Uttarakhand",
    language: "Hindi, English",
    email: "lawyer37@aa.com",
    password: "123456",
    rate: "21",
    id: "NATIONAL_ID_37",
    barID: "BAR_ID_37",
    barYear: "43963",
    specialties: "Divorce & Child Custody, Property & Real Estate",
    summary:
      "I have been practicing from last 5 years before the Hon'ble Rajasthan HC, District Courts, Tribunals amd other forums. I'm a third generation lawyer having 40 plus years of goodwill and standing in the legal industry.",
  },
  {
    First_Name: "Lawyer38",
    Last_Name: "Llast38",
    contact: "2200220038",
    city: "Kishanganj",
    state: "Bihar",
    language: "Hindi, English",
    email: "lawyer38@aa.com",
    password: "123456",
    rate: "30",
    id: "NATIONAL_ID_38",
    barID: "BAR_ID_38",
    barYear: "36519",
    specialties: "Property & Real Estate, Cheque Bounce & Money Recovery",
    summary:
      "With 30 years of professional lineage as a second-generation lawyer in the Delhi High Court, Bombay High Court Karnataka High Court, Telangana High Court, District Courts across India and Supreme Court Of India. I am a seasoned legal expert with a wealth of experience in a wide range of legal matters. As a representative of the Delhi Police, I am well-versed in providing legal advisory, drafting, and representing services across various courts in India. I have specialized expertise in civil, criminal, and corporate laws, with particular proficiency in drafting suits, writs, petitions, appeals, revisions, and complaints related to debt recovery, cheque bounce matters, rent control act, property disputes, and matrimonial disputes. Additionally, I have extensive experience in handling consumer complaints, FSSAI-related matters, and service matters. My expertise in drafting quality legal documents and agreements is unparalleled. I have experience drafting and professionally vetting a range of legal documents and agreements, including Master Service Agreements, Commercial Leases, Consortium Agreements, Tripartite Agreements, RFQs, Letters of Intent, MOUs, Celebrity Agreements, Endorsement Agreements, License Agreements, Sub-Licensing Agreements, Sub-Contracting, Third-Party Agreements, Sale Deeds, Corporate Lease Agreements, and Development Agreements in the real estate sector. With my extensive knowledge and experience in the legal industry, I am confident in my ability to provide expert legal advice and support to clients across a range of industries and sectors.",
  },
  {
    First_Name: "Lawyer39",
    Last_Name: "Llast39",
    contact: "2200220039",
    city: "Patna",
    state: "Bihar",
    language: "Hindi, English",
    email: "lawyer39@aa.com",
    password: "123456",
    rate: "31",
    id: "NATIONAL_ID_39",
    barID: "BAR_ID_39",
    barYear: "36695",
    specialties: " Cheque Bounce & Money Recovery, Employment Issues",
    summary: "Lawyer Supreme court of India",
  },
  {
    First_Name: "Lawyer40",
    Last_Name: "Llast40",
    contact: "2200220040",
    city: "Unhel",
    state: "Madhya Pradesh",
    language: "Hindi, English",
    email: "lawyer40@aa.com",
    password: "123456",
    rate: "37",
    id: "NATIONAL_ID_40",
    barID: "BAR_ID_40",
    barYear: "40940",
    specialties: "Employment Issues, Consumer Protection, Civil Matter",
    summary: "dealing with civil, criminal, Dop, Place, mvop ect cases. ",
  },
  {
    First_Name: "Lawyer41",
    Last_Name: "Llast41",
    contact: "2200220041",
    city: "Vidisha",
    state: "Madhya Pradesh",
    language: "Hindi, English",
    email: "lawyer41@aa.com",
    password: "123456",
    rate: "24",
    id: "NATIONAL_ID_41",
    barID: "BAR_ID_41",
    barYear: "34380",
    specialties: "Consumer Protection, Civil Matters, Cyber Crime",
    summary: "Fifteen years experience lawyer.",
  },
  {
    First_Name: "Lawyer42",
    Last_Name: "Llast42",
    contact: "2200220042",
    city: "Waraseoni",
    state: "Madhya Pradesh",
    language: "Hindi, English",
    email: "lawyer42@aa.com",
    password: "123456",
    rate: "37",
    id: "NATIONAL_ID_42",
    barID: "BAR_ID_42",
    barYear: "33382",
    specialties:
      "Divorce & Child Custody, Property & Real Estate, Civil Matters, Cyber Crime, ",
    summary:
      "Advocate A. Ashok Kumar has been practising for 9 years in Civil, Criminal & Family matters cases and handling the matters ethically and professionally. He also handles the NI Act, Recovery, Medical N",
  },
  {
    First_Name: "Lawyer43",
    Last_Name: "Llast43",
    contact: "2200220043",
    city: "Aron",
    state: "Madhya Pradesh",
    language: "Hindi, English",
    email: "lawyer43@aa.com",
    password: "123456",
    rate: "25",
    id: "NATIONAL_ID_43",
    barID: "BAR_ID_43",
    barYear: "37843",
    specialties: "Civil Matters, Cyber Crime, Other Legal Problem",
    summary: "Summary written by Lawyer",
  },
  {
    First_Name: "Lawyer44",
    Last_Name: "Llast44",
    contact: "2200220044",
    city: "Sarangarh",
    state: "Chhattisgarh",
    language: "Hindi, English",
    email: "lawyer44@aa.com",
    password: "123456",
    rate: "42",
    id: "NATIONAL_ID_44",
    barID: "BAR_ID_44",
    barYear: "36833",
    specialties:
      "Property & Real Estate, Consumer Protection, Civil Matters, Cyber Crime, Criminal Matter",
    summary:
      "I have been practicing from last 5 years before the Hon'ble Rajasthan HC, District Courts, Tribunals amd other forums. I'm a third generation lawyer having 40 plus years of goodwill and standing in the legal industry.",
  },
  {
    First_Name: "Lawyer45",
    Last_Name: "Llast45",
    contact: "2200220045",
    city: "Takhatpur",
    state: "Chhattisgarh",
    language: "Hindi, English",
    email: "lawyer45@aa.com",
    password: "123456",
    rate: "35",
    id: "NATIONAL_ID_45",
    barID: "BAR_ID_45",
    barYear: "40482",
    specialties: "Divorce & Child Custody, Property & Real Estate, Cyber Crime",
    summary:
      "With 30 years of professional lineage as a second-generation lawyer in the Delhi High Court, Bombay High Court Karnataka High Court, Telangana High Court, District Courts across India and Supreme Court Of India. I am a seasoned legal expert with a wealth of experience in a wide range of legal matters. As a representative of the Delhi Police, I am well-versed in providing legal advisory, drafting, and representing services across various courts in India. I have specialized expertise in civil, criminal, and corporate laws, with particular proficiency in drafting suits, writs, petitions, appeals, revisions, and complaints related to debt recovery, cheque bounce matters, rent control act, property disputes, and matrimonial disputes. Additionally, I have extensive experience in handling consumer complaints, FSSAI-related matters, and service matters. My expertise in drafting quality legal documents and agreements is unparalleled. I have experience drafting and professionally vetting a range of legal documents and agreements, including Master Service Agreements, Commercial Leases, Consortium Agreements, Tripartite Agreements, RFQs, Letters of Intent, MOUs, Celebrity Agreements, Endorsement Agreements, License Agreements, Sub-Licensing Agreements, Sub-Contracting, Third-Party Agreements, Sale Deeds, Corporate Lease Agreements, and Development Agreements in the real estate sector. With my extensive knowledge and experience in the legal industry, I am confident in my ability to provide expert legal advice and support to clients across a range of industries and sectors.",
  },
  {
    First_Name: "Lawyer46",
    Last_Name: "Llast46",
    contact: "2200220046",
    city: "Umarkot",
    state: "Chhattisgarh",
    language: "Hindi, English",
    email: "lawyer46@aa.com",
    password: "123456",
    rate: "46",
    id: "NATIONAL_ID_46",
    barID: "BAR_ID_46",
    barYear: "33831",
    specialties: "Divorce & Child Custody, Property & Real Estate",
    summary: "Lawyer Supreme court of India",
  },
  {
    First_Name: "Lawyer47",
    Last_Name: "Llast47",
    contact: "2200220047",
    city: "Uttar Bastar Kanker",
    state: "Chhattisgarh",
    language: "Hindi, English",
    email: "lawyer47@aa.com",
    password: "123456",
    rate: "26",
    id: "NATIONAL_ID_47",
    barID: "BAR_ID_47",
    barYear: "34894",
    specialties: "Property & Real Estate, Cheque Bounce & Money Recovery",
    summary: "dealing with civil, criminal, Dop, Place, mvop ect cases. ",
  },
  {
    First_Name: "Lawyer48",
    Last_Name: "Llast48",
    contact: "2200220048",
    city: "Unakoti",
    state: "Tripura",
    language: "Hindi, English",
    email: "lawyer48@aa.com",
    password: "123456",
    rate: "30",
    id: "NATIONAL_ID_48",
    barID: "BAR_ID_48",
    barYear: "44058",
    specialties: " Cheque Bounce & Money Recovery, Employment Issues",
    summary: "Fifteen years experience lawyer.",
  },
  {
    First_Name: "Lawyer49",
    Last_Name: "Llast49",
    contact: "2200220049",
    city: "West Tripura",
    state: "Tripura",
    language: "Hindi, English",
    email: "lawyer49@aa.com",
    password: "123456",
    rate: "41",
    id: "NATIONAL_ID_49",
    barID: "BAR_ID_49",
    barYear: "35094",
    specialties: "Employment Issues, Consumer Protection, Civil Matter",
    summary:
      "Advocate A. Ashok Kumar has been practising for 9 years in Civil, Criminal & Family matters cases and handling the matters ethically and professionally. He also handles the NI Act, Recovery, Medical N",
  },
  {
    First_Name: "Lawyer50",
    Last_Name: "Llast50",
    contact: "2200220050",
    city: "Ambasa",
    state: "Tripura",
    language: "Hindi, English",
    email: "lawyer50@aa.com",
    password: "123456",
    rate: "43",
    id: "NATIONAL_ID_50",
    barID: "BAR_ID_50",
    barYear: "34276",
    specialties: "Consumer Protection, Civil Matters, Cyber Crime",
    summary: "Summary written by Lawyer",
  },
  {
    First_Name: "Lawyer51",
    Last_Name: "Llast51",
    contact: "2200220051",
    city: "Hyderabad",
    state: "Telangana",
    language: "Hindi, English, Telegu",
    email: "lawyer51@aa.com",
    password: "123456",
    rate: "49",
    id: "NATIONAL_ID_51",
    barID: "BAR_ID_51",
    barYear: "33421",
    specialties:
      "Divorce & Child Custody, Property & Real Estate, Civil Matters, Cyber Crime, ",
    summary:
      "I have been practicing from last 5 years before the Hon'ble Rajasthan HC, District Courts, Tribunals amd other forums. I'm a third generation lawyer having 40 plus years of goodwill and standing in the legal industry.",
  },
  {
    First_Name: "Lawyer52",
    Last_Name: "Llast52",
    contact: "2200220052",
    city: "Secunderabad",
    state: "Telangana",
    language: "Hindi, English, Telegu",
    email: "lawyer52@aa.com",
    password: "123456",
    rate: "26",
    id: "NATIONAL_ID_52",
    barID: "BAR_ID_52",
    barYear: "41389",
    specialties: "Civil Matters, Cyber Crime, Other Legal Problem",
    summary:
      "With 30 years of professional lineage as a second-generation lawyer in the Delhi High Court, Bombay High Court Karnataka High Court, Telangana High Court, District Courts across India and Supreme Court Of India. I am a seasoned legal expert with a wealth of experience in a wide range of legal matters. As a representative of the Delhi Police, I am well-versed in providing legal advisory, drafting, and representing services across various courts in India. I have specialized expertise in civil, criminal, and corporate laws, with particular proficiency in drafting suits, writs, petitions, appeals, revisions, and complaints related to debt recovery, cheque bounce matters, rent control act, property disputes, and matrimonial disputes. Additionally, I have extensive experience in handling consumer complaints, FSSAI-related matters, and service matters. My expertise in drafting quality legal documents and agreements is unparalleled. I have experience drafting and professionally vetting a range of legal documents and agreements, including Master Service Agreements, Commercial Leases, Consortium Agreements, Tripartite Agreements, RFQs, Letters of Intent, MOUs, Celebrity Agreements, Endorsement Agreements, License Agreements, Sub-Licensing Agreements, Sub-Contracting, Third-Party Agreements, Sale Deeds, Corporate Lease Agreements, and Development Agreements in the real estate sector. With my extensive knowledge and experience in the legal industry, I am confident in my ability to provide expert legal advice and support to clients across a range of industries and sectors.",
  },
  {
    First_Name: "Lawyer53",
    Last_Name: "Llast53",
    contact: "2200220053",
    city: "North Goa",
    state: "Goa",
    language: "Hindi, English",
    email: "lawyer53@aa.com",
    password: "123456",
    rate: "38",
    id: "NATIONAL_ID_53",
    barID: "BAR_ID_53",
    barYear: "35776",
    specialties:
      "Property & Real Estate, Consumer Protection, Civil Matters, Cyber Crime, Criminal Matter",
    summary: "Lawyer Supreme court of India",
  },
  {
    First_Name: "Lawyer54",
    Last_Name: "Llast54",
    contact: "2200220054",
    city: "South Goa",
    state: "Goa",
    language: "Hindi, English",
    email: "lawyer54@aa.com",
    password: "123456",
    rate: "45",
    id: "NATIONAL_ID_54",
    barID: "BAR_ID_54",
    barYear: "34535",
    specialties: "Divorce & Child Custody, Property & Real Estate, Cyber Crime",
    summary: "dealing with civil, criminal, Dop, Place, mvop ect cases. ",
  },
  {
    First_Name: "Lawyer55",
    Last_Name: "Llast55",
    contact: "2200220055",
    city: "Karaikal",
    state: "Puducherry",
    language: "Hindi, English",
    email: "lawyer55@aa.com",
    password: "123456",
    rate: "30",
    id: "NATIONAL_ID_55",
    barID: "BAR_ID_55",
    barYear: "37839",
    specialties: "Divorce & Child Custody, Property & Real Estate",
    summary: "Fifteen years experience lawyer.",
  },
  {
    First_Name: "Lawyer56",
    Last_Name: "Llast56",
    contact: "2200220056",
    city: "Mahe",
    state: "Puducherry",
    language: "Hindi, English",
    email: "lawyer56@aa.com",
    password: "123456",
    rate: "40",
    id: "NATIONAL_ID_56",
    barID: "BAR_ID_56",
    barYear: "38663",
    specialties: "Property & Real Estate, Cheque Bounce & Money Recovery",
    summary:
      "Advocate A. Ashok Kumar has been practising for 9 years in Civil, Criminal & Family matters cases and handling the matters ethically and professionally. He also handles the NI Act, Recovery, Medical N",
  },
  {
    First_Name: "Lawyer57",
    Last_Name: "Llast57",
    contact: "2200220057",
    city: "West Jaintia Hills",
    state: "Meghalaya",
    language: "Hindi, English",
    email: "lawyer57@aa.com",
    password: "123456",
    rate: "38",
    id: "NATIONAL_ID_57",
    barID: "BAR_ID_57",
    barYear: "34894",
    specialties: " Cheque Bounce & Money Recovery, Employment Issues",
    summary: "Summary written by Lawyer",
  },
  {
    First_Name: "Lawyer58",
    Last_Name: "Llast58",
    contact: "2200220058",
    city: "West Khasi Hills",
    state: "Meghalaya",
    language: "Hindi, English",
    email: "lawyer58@aa.com",
    password: "123456",
    rate: "26",
    id: "NATIONAL_ID_58",
    barID: "BAR_ID_58",
    barYear: "33520",
    specialties: "Employment Issues, Consumer Protection, Civil Matter",
    summary:
      "I have been practicing from last 5 years before the Hon'ble Rajasthan HC, District Courts, Tribunals amd other forums. I'm a third generation lawyer having 40 plus years of goodwill and standing in the legal industry.",
  },
  {
    First_Name: "Lawyer59",
    Last_Name: "Llast59",
    contact: "2200220059",
    city: "Sini",
    state: "Jharkhand",
    language: "Hindi, English",
    email: "lawyer59@aa.com",
    password: "123456",
    rate: "34",
    id: "NATIONAL_ID_59",
    barID: "BAR_ID_59",
    barYear: "44452",
    specialties: "Consumer Protection, Civil Matters, Cyber Crime",
    summary:
      "With 30 years of professional lineage as a second-generation lawyer in the Delhi High Court, Bombay High Court Karnataka High Court, Telangana High Court, District Courts across India and Supreme Court Of India. I am a seasoned legal expert with a wealth of experience in a wide range of legal matters. As a representative of the Delhi Police, I am well-versed in providing legal advisory, drafting, and representing services across various courts in India. I have specialized expertise in civil, criminal, and corporate laws, with particular proficiency in drafting suits, writs, petitions, appeals, revisions, and complaints related to debt recovery, cheque bounce matters, rent control act, property disputes, and matrimonial disputes. Additionally, I have extensive experience in handling consumer complaints, FSSAI-related matters, and service matters. My expertise in drafting quality legal documents and agreements is unparalleled. I have experience drafting and professionally vetting a range of legal documents and agreements, including Master Service Agreements, Commercial Leases, Consortium Agreements, Tripartite Agreements, RFQs, Letters of Intent, MOUs, Celebrity Agreements, Endorsement Agreements, License Agreements, Sub-Licensing Agreements, Sub-Contracting, Third-Party Agreements, Sale Deeds, Corporate Lease Agreements, and Development Agreements in the real estate sector. With my extensive knowledge and experience in the legal industry, I am confident in my ability to provide expert legal advice and support to clients across a range of industries and sectors.",
  },
  {
    First_Name: "Lawyer60",
    Last_Name: "Llast60",
    contact: "2200220060",
    city: "Sarubera",
    state: "Jharkhand",
    language: "Hindi, English",
    email: "lawyer60@aa.com",
    password: "123456",
    rate: "43",
    id: "NATIONAL_ID_60",
    barID: "BAR_ID_60",
    barYear: "38414",
    specialties:
      "Divorce & Child Custody, Property & Real Estate, Civil Matters, Cyber Crime, ",
    summary: "Lawyer Supreme court of India",
  },
  {
    First_Name: "Lawyer61",
    Last_Name: "Llast61",
    contact: "2200220061",
    city: "Bengaluru",
    state: "Karnataka",
    language: "Hindi, English, Kannada",
    email: "lawyer61@aa.com",
    password: "123456",
    rate: "44",
    id: "NATIONAL_ID_61",
    barID: "BAR_ID_61",
    barYear: "42519",
    specialties: "Civil Matters, Cyber Crime, Other Legal Problem",
    summary: "dealing with civil, criminal, Dop, Place, mvop ect cases. ",
  },
  {
    First_Name: "Lawyer62",
    Last_Name: "Llast62",
    contact: "2200220062",
    city: "Chintamani",
    state: "Karnataka",
    language: "Hindi, English, Kannada",
    email: "lawyer62@aa.com",
    password: "123456",
    rate: "42",
    id: "NATIONAL_ID_62",
    barID: "BAR_ID_62",
    barYear: "33841",
    specialties:
      "Property & Real Estate, Consumer Protection, Civil Matters, Cyber Crime, Criminal Matter",
    summary: "Fifteen years experience lawyer.",
  },
  {
    First_Name: "Lawyer63",
    Last_Name: "Llast63",
    contact: "2200220063",
    city: "Amritsar",
    state: "Punjab",
    language: "Hindi, English, Punjabi",
    email: "lawyer63@aa.com",
    password: "123456",
    rate: "24",
    id: "NATIONAL_ID_63",
    barID: "BAR_ID_63",
    barYear: "37064",
    specialties: "Divorce & Child Custody, Property & Real Estate, Cyber Crime",
    summary:
      "Advocate A. Ashok Kumar has been practising for 9 years in Civil, Criminal & Family matters cases and handling the matters ethically and professionally. He also handles the NI Act, Recovery, Medical N",
  },
  {
    First_Name: "Lawyer64",
    Last_Name: "Llast64",
    contact: "2200220064",
    city: "Gurdaspur",
    state: "Punjab",
    language: "Hindi, English, Punjabi",
    email: "lawyer64@aa.com",
    password: "123456",
    rate: "29",
    id: "NATIONAL_ID_64",
    barID: "BAR_ID_64",
    barYear: "34043",
    specialties: "Divorce & Child Custody, Property & Real Estate",
    summary: "Summary written by Lawyer",
  },
  {
    First_Name: "Lawyer65",
    Last_Name: "Llast65",
    contact: "2200220065",
    city: "Jalandhar",
    state: "Punjab",
    language: "Hindi, English, Punjabi",
    email: "lawyer65@aa.com",
    password: "123456",
    rate: "46",
    id: "NATIONAL_ID_65",
    barID: "BAR_ID_65",
    barYear: "42642",
    specialties: "Property & Real Estate, Cheque Bounce & Money Recovery",
    summary:
      "I have been practicing from last 5 years before the Hon'ble Rajasthan HC, District Courts, Tribunals amd other forums. I'm a third generation lawyer having 40 plus years of goodwill and standing in the legal industry.",
  },
  {
    First_Name: "Lawyer66",
    Last_Name: "Llast66",
    contact: "2200220066",
    city: "Ludhiana",
    state: "Punjab",
    language: "Hindi, English, Punjabi",
    email: "lawyer66@aa.com",
    password: "123456",
    rate: "35",
    id: "NATIONAL_ID_66",
    barID: "BAR_ID_66",
    barYear: "43263",
    specialties: " Cheque Bounce & Money Recovery, Employment Issues",
    summary:
      "With 30 years of professional lineage as a second-generation lawyer in the Delhi High Court, Bombay High Court Karnataka High Court, Telangana High Court, District Courts across India and Supreme Court Of India. I am a seasoned legal expert with a wealth of experience in a wide range of legal matters. As a representative of the Delhi Police, I am well-versed in providing legal advisory, drafting, and representing services across various courts in India. I have specialized expertise in civil, criminal, and corporate laws, with particular proficiency in drafting suits, writs, petitions, appeals, revisions, and complaints related to debt recovery, cheque bounce matters, rent control act, property disputes, and matrimonial disputes. Additionally, I have extensive experience in handling consumer complaints, FSSAI-related matters, and service matters. My expertise in drafting quality legal documents and agreements is unparalleled. I have experience drafting and professionally vetting a range of legal documents and agreements, including Master Service Agreements, Commercial Leases, Consortium Agreements, Tripartite Agreements, RFQs, Letters of Intent, MOUs, Celebrity Agreements, Endorsement Agreements, License Agreements, Sub-Licensing Agreements, Sub-Contracting, Third-Party Agreements, Sale Deeds, Corporate Lease Agreements, and Development Agreements in the real estate sector. With my extensive knowledge and experience in the legal industry, I am confident in my ability to provide expert legal advice and support to clients across a range of industries and sectors.",
  },
  {
    First_Name: "Lawyer67",
    Last_Name: "Llast67",
    contact: "2200220067",
    city: "Mohali",
    state: "Punjab",
    language: "Hindi, English, Punjabi",
    email: "lawyer67@aa.com",
    password: "123456",
    rate: "22",
    id: "NATIONAL_ID_67",
    barID: "BAR_ID_67",
    barYear: "34636",
    specialties: "Employment Issues, Consumer Protection, Civil Matter",
    summary: "Lawyer Supreme court of India",
  },
  {
    First_Name: "Lawyer68",
    Last_Name: "Llast68",
    contact: "2200220068",
    city: "Patiala",
    state: "Punjab",
    language: "Hindi, English, Punjabi",
    email: "lawyer68@aa.com",
    password: "123456",
    rate: "22",
    id: "NATIONAL_ID_68",
    barID: "BAR_ID_68",
    barYear: "39025",
    specialties: "Consumer Protection, Civil Matters, Cyber Crime",
    summary: "dealing with civil, criminal, Dop, Place, mvop ect cases. ",
  },
  {
    First_Name: "Lawyer69",
    Last_Name: "Llast69",
    contact: "2200220069",
    city: "Ahmedabad",
    state: "Gujarat",
    language: "Hindi, English, Gujrati, Punjabi, Bengali",
    email: "lawyer69@aa.com",
    password: "123456",
    rate: "32",
    id: "NATIONAL_ID_69",
    barID: "BAR_ID_69",
    barYear: "39448",
    specialties:
      "Divorce & Child Custody, Property & Real Estate, Civil Matters, Cyber Crime, ",
    summary: "Fifteen years experience lawyer.",
  },
  {
    First_Name: "Lawyer70",
    Last_Name: "Llast70",
    contact: "2200220070",
    city: "Gandhinagar",
    state: "Gujarat",
    language: "Hindi, English, Gujrati, Punjabi, Bengali",
    email: "lawyer70@aa.com",
    password: "123456",
    rate: "27",
    id: "NATIONAL_ID_70",
    barID: "BAR_ID_70",
    barYear: "37352",
    specialties: "Civil Matters, Cyber Crime, Other Legal Problem",
    summary:
      "Advocate A. Ashok Kumar has been practising for 9 years in Civil, Criminal & Family matters cases and handling the matters ethically and professionally. He also handles the NI Act, Recovery, Medical N",
  },
  {
    First_Name: "Lawyer71",
    Last_Name: "Llast71",
    contact: "2200220071",
    city: "East District",
    state: "Sikkim",
    language: "Hindi, English, Assamese",
    email: "lawyer71@aa.com",
    password: "123456",
    rate: "23",
    id: "NATIONAL_ID_71",
    barID: "BAR_ID_71",
    barYear: "41368",
    specialties:
      "Property & Real Estate, Consumer Protection, Civil Matters, Cyber Crime, Criminal Matter",
    summary: "Summary written by Lawyer",
  },
  {
    First_Name: "Lawyer72",
    Last_Name: "Llast72",
    contact: "2200220072",
    city: "North District",
    state: "Sikkim",
    language: "Hindi, English, Assamese",
    email: "lawyer72@aa.com",
    password: "123456",
    rate: "39",
    id: "NATIONAL_ID_72",
    barID: "BAR_ID_72",
    barYear: "44877",
    specialties: "Divorce & Child Custody, Property & Real Estate, Cyber Crime",
    summary:
      "I have been practicing from last 5 years before the Hon'ble Rajasthan HC, District Courts, Tribunals amd other forums. I'm a third generation lawyer having 40 plus years of goodwill and standing in the legal industry.",
  },
  {
    First_Name: "Lawyer73",
    Last_Name: "Llast73",
    contact: "2200220073",
    city: "West District",
    state: "Sikkim",
    language: "Hindi, English, Assamese",
    email: "lawyer73@aa.com",
    password: "123456",
    rate: "45",
    id: "NATIONAL_ID_73",
    barID: "BAR_ID_73",
    barYear: "43048",
    specialties: "Divorce & Child Custody, Property & Real Estate",
    summary:
      "With 30 years of professional lineage as a second-generation lawyer in the Delhi High Court, Bombay High Court Karnataka High Court, Telangana High Court, District Courts across India and Supreme Court Of India. I am a seasoned legal expert with a wealth of experience in a wide range of legal matters. As a representative of the Delhi Police, I am well-versed in providing legal advisory, drafting, and representing services across various courts in India. I have specialized expertise in civil, criminal, and corporate laws, with particular proficiency in drafting suits, writs, petitions, appeals, revisions, and complaints related to debt recovery, cheque bounce matters, rent control act, property disputes, and matrimonial disputes. Additionally, I have extensive experience in handling consumer complaints, FSSAI-related matters, and service matters. My expertise in drafting quality legal documents and agreements is unparalleled. I have experience drafting and professionally vetting a range of legal documents and agreements, including Master Service Agreements, Commercial Leases, Consortium Agreements, Tripartite Agreements, RFQs, Letters of Intent, MOUs, Celebrity Agreements, Endorsement Agreements, License Agreements, Sub-Licensing Agreements, Sub-Contracting, Third-Party Agreements, Sale Deeds, Corporate Lease Agreements, and Development Agreements in the real estate sector. With my extensive knowledge and experience in the legal industry, I am confident in my ability to provide expert legal advice and support to clients across a range of industries and sectors.",
  },
  {
    First_Name: "Lawyer74",
    Last_Name: "Llast74",
    contact: "2200220074",
    city: "Guwahati",
    state: "Assam",
    language: "Hindi, English, Assamese",
    email: "lawyer74@aa.com",
    password: "123456",
    rate: "36",
    id: "NATIONAL_ID_74",
    barID: "BAR_ID_74",
    barYear: "43587",
    specialties: "Property & Real Estate, Cheque Bounce & Money Recovery",
    summary: "Lawyer Supreme court of India",
  },
  {
    First_Name: "Lawyer75",
    Last_Name: "Llast75",
    contact: "2200220075",
    city: "North Lakhimpur",
    state: "Assam",
    language: "Hindi, English, Assamese",
    email: "lawyer75@aa.com",
    password: "123456",
    rate: "24",
    id: "NATIONAL_ID_75",
    barID: "BAR_ID_75",
    barYear: "40448",
    specialties: " Cheque Bounce & Money Recovery, Employment Issues",
    summary: "dealing with civil, criminal, Dop, Place, mvop ect cases. ",
  },
  {
    First_Name: "Lawyer76",
    Last_Name: "Llast76",
    contact: "2200220076",
    city: "Tuensang District",
    state: "Nagaland",
    language: "Hindi, English, Assamese",
    email: "lawyer76@aa.com",
    password: "123456",
    rate: "21",
    id: "NATIONAL_ID_76",
    barID: "BAR_ID_76",
    barYear: "32653",
    specialties: "Employment Issues, Consumer Protection, Civil Matter",
    summary: "Fifteen years experience lawyer.",
  },
  {
    First_Name: "Lawyer77",
    Last_Name: "Llast77",
    contact: "2200220077",
    city: "Daman",
    state: "Dadra and Nagar Haveli and Daman and Diu",
    language: "Hindi, English, Gujrati",
    email: "lawyer77@aa.com",
    password: "123456",
    rate: "35",
    id: "NATIONAL_ID_77",
    barID: "BAR_ID_77",
    barYear: "36283",
    specialties: "Consumer Protection, Civil Matters, Cyber Crime",
    summary:
      "Advocate A. Ashok Kumar has been practising for 9 years in Civil, Criminal & Family matters cases and handling the matters ethically and professionally. He also handles the NI Act, Recovery, Medical N",
  },
  {
    First_Name: "Lawyer78",
    Last_Name: "Llast78",
    contact: "2200220078",
    city: "Diu",
    state: "Dadra and Nagar Haveli and Daman and Diu",
    language: "Hindi, English, Gujrati",
    email: "lawyer78@aa.com",
    password: "123456",
    rate: "22",
    id: "NATIONAL_ID_78",
    barID: "BAR_ID_78",
    barYear: "36122",
    specialties:
      "Divorce & Child Custody, Property & Real Estate, Civil Matters, Cyber Crime, ",
    summary: "Summary written by Lawyer",
  },
  {
    First_Name: "Lawyer79",
    Last_Name: "Llast79",
    contact: "2200220079",
    city: "Talcher",
    state: "Odisha",
    language: "Hindi, English, Odia",
    email: "lawyer79@aa.com",
    password: "123456",
    rate: "48",
    id: "NATIONAL_ID_79",
    barID: "BAR_ID_79",
    barYear: "36882",
    specialties: "Civil Matters, Cyber Crime, Other Legal Problem",
    summary:
      "I have been practicing from last 5 years before the Hon'ble Rajasthan HC, District Courts, Tribunals amd other forums. I'm a third generation lawyer having 40 plus years of goodwill and standing in the legal industry.",
  },
  {
    First_Name: "Lawyer80",
    Last_Name: "Llast80",
    contact: "2200220080",
    city: "Udayagiri",
    state: "Odisha",
    language: "Hindi, English, Odia",
    email: "lawyer80@aa.com",
    password: "123456",
    rate: "32",
    id: "NATIONAL_ID_80",
    barID: "BAR_ID_80",
    barYear: "44397",
    specialties:
      "Property & Real Estate, Consumer Protection, Civil Matters, Cyber Crime, Criminal Matter",
    summary:
      "With 30 years of professional lineage as a second-generation lawyer in the Delhi High Court, Bombay High Court Karnataka High Court, Telangana High Court, District Courts across India and Supreme Court Of India. I am a seasoned legal expert with a wealth of experience in a wide range of legal matters. As a representative of the Delhi Police, I am well-versed in providing legal advisory, drafting, and representing services across various courts in India. I have specialized expertise in civil, criminal, and corporate laws, with particular proficiency in drafting suits, writs, petitions, appeals, revisions, and complaints related to debt recovery, cheque bounce matters, rent control act, property disputes, and matrimonial disputes. Additionally, I have extensive experience in handling consumer complaints, FSSAI-related matters, and service matters. My expertise in drafting quality legal documents and agreements is unparalleled. I have experience drafting and professionally vetting a range of legal documents and agreements, including Master Service Agreements, Commercial Leases, Consortium Agreements, Tripartite Agreements, RFQs, Letters of Intent, MOUs, Celebrity Agreements, Endorsement Agreements, License Agreements, Sub-Licensing Agreements, Sub-Contracting, Third-Party Agreements, Sale Deeds, Corporate Lease Agreements, and Development Agreements in the real estate sector. With my extensive knowledge and experience in the legal industry, I am confident in my ability to provide expert legal advice and support to clients across a range of industries and sectors.",
  },
  {
    First_Name: "Lawyer81",
    Last_Name: "Llast81",
    contact: "2200220081",
    city: "Serchhip",
    state: "Mizoram",
    language: "Hindi, English, Assamese",
    email: "lawyer81@aa.com",
    password: "123456",
    rate: "40",
    id: "NATIONAL_ID_81",
    barID: "BAR_ID_81",
    barYear: "39581",
    specialties: "Divorce & Child Custody, Property & Real Estate, Cyber Crime",
    summary: "Lawyer Supreme court of India",
  },
  {
    First_Name: "Lawyer82",
    Last_Name: "Llast82",
    contact: "2200220082",
    city: "Saitlaw",
    state: "Mizoram",
    language: "Hindi, English, Assamese",
    email: "lawyer82@aa.com",
    password: "123456",
    rate: "23",
    id: "NATIONAL_ID_82",
    barID: "BAR_ID_82",
    barYear: "38171",
    specialties: "Divorce & Child Custody, Property & Real Estate",
    summary: "dealing with civil, criminal, Dop, Place, mvop ect cases. ",
  },
  {
    First_Name: "Lawyer83",
    Last_Name: "Llast83",
    contact: "2200220083",
    city: "Upper Subansiri",
    state: "Arunachal Pradesh",
    language: "Hindi, English",
    email: "lawyer83@aa.com",
    password: "123456",
    rate: "49",
    id: "NATIONAL_ID_83",
    barID: "BAR_ID_83",
    barYear: "35411",
    specialties: "Property & Real Estate, Cheque Bounce & Money Recovery",
    summary: "Fifteen years experience lawyer.",
  },
  {
    First_Name: "Lawyer84",
    Last_Name: "Llast84",
    contact: "2200220084",
    city: "Kargil",
    state: "Ladakh",
    language: "Hindi, English",
    email: "lawyer84@aa.com",
    password: "123456",
    rate: "42",
    id: "NATIONAL_ID_84",
    barID: "BAR_ID_84",
    barYear: "44683",
    specialties: " Cheque Bounce & Money Recovery, Employment Issues",
    summary:
      "Advocate A. Ashok Kumar has been practising for 9 years in Civil, Criminal & Family matters cases and handling the matters ethically and professionally. He also handles the NI Act, Recovery, Medical N",
  },
  {
    First_Name: "Lawyer85",
    Last_Name: "Llast85",
    contact: "2200220085",
    city: "Cochin",
    state: "Kerala",
    language: "Hindi, English,Malayalam",
    email: "lawyer85@aa.com",
    password: "123456",
    rate: "25",
    id: "NATIONAL_ID_85",
    barID: "BAR_ID_85",
    barYear: "41590",
    specialties: "Employment Issues, Consumer Protection, Civil Matter",
    summary: "Summary written by Lawyer",
  },
  {
    First_Name: "Lawyer86",
    Last_Name: "Llast86",
    contact: "2200220086",
    city: "Thiruvananthapuram",
    state: "Kerala",
    language: "Hindi, English,Malayalam",
    email: "lawyer86@aa.com",
    password: "123456",
    rate: "44",
    id: "NATIONAL_ID_86",
    barID: "BAR_ID_86",
    barYear: "37247",
    specialties: "Consumer Protection, Civil Matters, Cyber Crime",
    summary:
      "I have been practicing from last 5 years before the Hon'ble Rajasthan HC, District Courts, Tribunals amd other forums. I'm a third generation lawyer having 40 plus years of goodwill and standing in the legal industry.",
  },
  {
    First_Name: "Lawyer87",
    Last_Name: "Llast87",
    contact: "2200220087",
    city: "Kavaratti",
    state: "Lakshadweep",
    language: "Hindi, English",
    email: "lawyer87@aa.com",
    password: "123456",
    rate: "30",
    id: "NATIONAL_ID_87",
    barID: "BAR_ID_87",
    barYear: "36298",
    specialties:
      "Divorce & Child Custody, Property & Real Estate, Civil Matters, Cyber Crime, ",
    summary:
      "With 30 years of professional lineage as a second-generation lawyer in the Delhi High Court, Bombay High Court Karnataka High Court, Telangana High Court, District Courts across India and Supreme Court Of India. I am a seasoned legal expert with a wealth of experience in a wide range of legal matters. As a representative of the Delhi Police, I am well-versed in providing legal advisory, drafting, and representing services across various courts in India. I have specialized expertise in civil, criminal, and corporate laws, with particular proficiency in drafting suits, writs, petitions, appeals, revisions, and complaints related to debt recovery, cheque bounce matters, rent control act, property disputes, and matrimonial disputes. Additionally, I have extensive experience in handling consumer complaints, FSSAI-related matters, and service matters. My expertise in drafting quality legal documents and agreements is unparalleled. I have experience drafting and professionally vetting a range of legal documents and agreements, including Master Service Agreements, Commercial Leases, Consortium Agreements, Tripartite Agreements, RFQs, Letters of Intent, MOUs, Celebrity Agreements, Endorsement Agreements, License Agreements, Sub-Licensing Agreements, Sub-Contracting, Third-Party Agreements, Sale Deeds, Corporate Lease Agreements, and Development Agreements in the real estate sector. With my extensive knowledge and experience in the legal industry, I am confident in my ability to provide expert legal advice and support to clients across a range of industries and sectors.",
  },
  {
    First_Name: "Lawyer88",
    Last_Name: "Llast88",
    contact: "2200220088",
    city: "Manali",
    state: "Himachal Pradesh",
    language: "Hindi, English, Punjabi",
    email: "lawyer88@aa.com",
    password: "123456",
    rate: "27",
    id: "NATIONAL_ID_88",
    barID: "BAR_ID_88",
    barYear: "33893",
    specialties: "Civil Matters, Cyber Crime, Other Legal Problem",
    summary: "Lawyer Supreme court of India",
  },
  {
    First_Name: "Lawyer89",
    Last_Name: "Llast89",
    contact: "2200220089",
    city: "Shimla",
    state: "Himachal Pradesh",
    language: "Hindi, English, Punjabi",
    email: "lawyer89@aa.com",
    password: "123456",
    rate: "46",
    id: "NATIONAL_ID_89",
    barID: "BAR_ID_89",
    barYear: "36316",
    specialties:
      "Property & Real Estate, Consumer Protection, Civil Matters, Cyber Crime, Criminal Matter",
    summary: "dealing with civil, criminal, Dop, Place, mvop ect cases. ",
  },
  {
    First_Name: "Lawyer90",
    Last_Name: "Llast90",
    contact: "2200220090",
    city: "Kolkata",
    state: "West Bengal",
    language: "Hindi, English, Bengali",
    email: "lawyer90@aa.com",
    password: "123456",
    rate: "22",
    id: "NATIONAL_ID_90",
    barID: "BAR_ID_90",
    barYear: "42024",
    specialties: "Divorce & Child Custody, Property & Real Estate, Cyber Crime",
    summary: "Fifteen years experience lawyer.",
  },
  {
    First_Name: "Lawyer91",
    Last_Name: "Llast91",
    contact: "2200220091",
    city: "Uttarpara Kotrung",
    state: "West Bengal",
    language: "Hindi, English, Bengali",
    email: "lawyer91@aa.com",
    password: "123456",
    rate: "27",
    id: "NATIONAL_ID_91",
    barID: "BAR_ID_91",
    barYear: "33998",
    specialties: "Divorce & Child Custody, Property & Real Estate",
    summary:
      "Advocate A. Ashok Kumar has been practising for 9 years in Civil, Criminal & Family matters cases and handling the matters ethically and professionally. He also handles the NI Act, Recovery, Medical N",
  },
  {
    First_Name: "Lawyer92",
    Last_Name: "Llast92",
    contact: "2200220092",
    city: "Chandigarh",
    state: "Chandigarh",
    language: "Hindi, English, Punjabi",
    email: "lawyer92@aa.com",
    password: "123456",
    rate: "28",
    id: "NATIONAL_ID_92",
    barID: "BAR_ID_92",
    barYear: "37146",
    specialties: "Property & Real Estate, Cheque Bounce & Money Recovery",
    summary: "Summary written by Lawyer",
  },
  {
    First_Name: "Lawyer93",
    Last_Name: "Llast93",
    contact: "2200220093",
    city: "Agra",
    state: "Uttar Pradesh",
    language: "Hindi, English, Punjabi",
    email: "lawyer93@aa.com",
    password: "123456",
    rate: "42",
    id: "NATIONAL_ID_93",
    barID: "BAR_ID_93",
    barYear: "41443",
    specialties: " Cheque Bounce & Money Recovery, Employment Issues",
    summary:
      "I have been practicing from last 5 years before the Hon'ble Rajasthan HC, District Courts, Tribunals amd other forums. I'm a third generation lawyer having 40 plus years of goodwill and standing in the legal industry.",
  },
  {
    First_Name: "Lawyer94",
    Last_Name: "Llast94",
    contact: "2200220094",
    city: "Ghaziabad",
    state: "Uttar Pradesh",
    language: "Hindi, English, Punjabi",
    email: "lawyer94@aa.com",
    password: "123456",
    rate: "32",
    id: "NATIONAL_ID_94",
    barID: "BAR_ID_94",
    barYear: "42643",
    specialties: "Employment Issues, Consumer Protection, Civil Matter",
    summary:
      "With 30 years of professional lineage as a second-generation lawyer in the Delhi High Court, Bombay High Court Karnataka High Court, Telangana High Court, District Courts across India and Supreme Court Of India. I am a seasoned legal expert with a wealth of experience in a wide range of legal matters. As a representative of the Delhi Police, I am well-versed in providing legal advisory, drafting, and representing services across various courts in India. I have specialized expertise in civil, criminal, and corporate laws, with particular proficiency in drafting suits, writs, petitions, appeals, revisions, and complaints related to debt recovery, cheque bounce matters, rent control act, property disputes, and matrimonial disputes. Additionally, I have extensive experience in handling consumer complaints, FSSAI-related matters, and service matters. My expertise in drafting quality legal documents and agreements is unparalleled. I have experience drafting and professionally vetting a range of legal documents and agreements, including Master Service Agreements, Commercial Leases, Consortium Agreements, Tripartite Agreements, RFQs, Letters of Intent, MOUs, Celebrity Agreements, Endorsement Agreements, License Agreements, Sub-Licensing Agreements, Sub-Contracting, Third-Party Agreements, Sale Deeds, Corporate Lease Agreements, and Development Agreements in the real estate sector. With my extensive knowledge and experience in the legal industry, I am confident in my ability to provide expert legal advice and support to clients across a range of industries and sectors.",
  },
  {
    First_Name: "Lawyer95",
    Last_Name: "Llast95",
    contact: "2200220095",
    city: "Lucknow",
    state: "Uttar Pradesh",
    language: "Hindi, English",
    email: "lawyer95@aa.com",
    password: "123456",
    rate: "28",
    id: "NATIONAL_ID_95",
    barID: "BAR_ID_95",
    barYear: "32858",
    specialties: "Consumer Protection, Civil Matters, Cyber Crime",
    summary: "Lawyer Supreme court of India",
  },
  {
    First_Name: "Lawyer96",
    Last_Name: "Llast96",
    contact: "2200220096",
    city: "Noida",
    state: "Uttar Pradesh",
    language: "Hindi, English",
    email: "lawyer96@aa.com",
    password: "123456",
    rate: "46",
    id: "NATIONAL_ID_96",
    barID: "BAR_ID_96",
    barYear: "43632",
    specialties:
      "Divorce & Child Custody, Property & Real Estate, Civil Matters, Cyber Crime, ",
    summary: "dealing with civil, criminal, Dop, Place, mvop ect cases. ",
  },
  {
    First_Name: "Lawyer97",
    Last_Name: "Llast97",
    contact: "2200220097",
    city: "Uttukkuli",
    state: "Tamil Nadu",
    language: "Hindi, English, Tamil, Malayalam",
    email: "lawyer97@aa.com",
    password: "123456",
    rate: "32",
    id: "NATIONAL_ID_97",
    barID: "BAR_ID_97",
    barYear: "43112",
    specialties: "Civil Matters, Cyber Crime, Other Legal Problem",
    summary: "Fifteen years experience lawyer.",
  },
  {
    First_Name: "Lawyer98",
    Last_Name: "Llast98",
    contact: "2200220098",
    city: "Ranipet",
    state: "Tamil Nadu",
    language: "Hindi, English, Tamil",
    email: "lawyer98@aa.com",
    password: "123456",
    rate: "35",
    id: "NATIONAL_ID_98",
    barID: "BAR_ID_98",
    barYear: "33399",
    specialties:
      "Property & Real Estate, Consumer Protection, Civil Matters, Cyber Crime, Criminal Matter",
    summary:
      "Advocate A. Ashok Kumar has been practising for 9 years in Civil, Criminal & Family matters cases and handling the matters ethically and professionally. He also handles the NI Act, Recovery, Medical N",
  },
  {
    First_Name: "Lawyer99",
    Last_Name: "Llast99",
    contact: "2200220099",
    city: "Bishnupur",
    state: "Manipur",
    language: "Hindi, English",
    email: "lawyer99@aa.com",
    password: "123456",
    rate: "27",
    id: "NATIONAL_ID_99",
    barID: "BAR_ID_99",
    barYear: "33122",
    specialties: "Divorce & Child Custody, Property & Real Estate, Cyber Crime",
    summary: "Summary written by Lawyer",
  },
  {
    First_Name: "Lawyer100",
    Last_Name: "Llast100",
    contact: "2200220100",
    city: "Churachandpur",
    state: "Manipur",
    language: "Hindi, English",
    email: "lawyer100@aa.com",
    password: "123456",
    rate: "37",
    id: "NATIONAL_ID_100",
    barID: "BAR_ID_100",
    barYear: "37059",
    specialties: "Divorce & Child Custody, Property & Real Estate",
    summary:
      "I have been practicing from last 5 years before the Hon'ble Rajasthan HC, District Courts, Tribunals amd other forums. I'm a third generation lawyer having 40 plus years of goodwill and standing in the legal industry.",
  },
];

export { users };
